site_name: yuusim
repo_url: https://github.com/UynajGI/yuusim
site_url: https://UynajGI.github.io/yuusim
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Yuunagi
edit_uri: edit/main/docs/
repo_name: UynajGI/yuusim
copyright: Maintained by <a href="https://UynajGI.com">UynajGI</a>.

nav:
  - Home: index.md
  - Modules:
      - Introduction: modules.md
      - Simulation: simulation/index.md
      - Input/Output: io/index.md
      - Utility: utils/index.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/yuusim"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UynajGI/yuusim
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/yuusim

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
